### ISSUE TITLE
MySQL error message

### ISSUE THREAD

**Issue by floyd-fuh** [augustd/burp-suite-error-message-checks#10]
I had a MySQL error thrown at me during a pentest that read as following in the HTTP response:

```
<title>Database error</ title>
</ head>
<body>
<h1>ERROR − database error .</h1>
<p>Illegal mix of collations (latin1_swedish_ci ,IMPLICIT) and (utf8_general_ci ,COERCIBLE)
for operation ’=’</p>
<p>
SELECT id , *REDACTED*
FROM users
WHERE name =
```

Therefore I suggest adding a regex like:

Illegal mix of collations \(.*\) and \(.*\) for operation

**Comment by adetlefsen-rms** [comment]
Thanks @floyd-fuh! 

If you load the match rules again you should be able to pick up that error now: https://github.com/augustd/burp-suite-error-message-checks/blob/master/src/main/resources/burp/match-rules.tab

**Comment by floyd-fuh** [comment]
Thanks!

But I just realized that in the "Error Message Checks" tab of Burp it doesn't matter if I click the Load button, it won't add the new MySQL error check. That's probably because Burp is caching the fetch of https://raw.githubusercontent.com/augustd/burp-suite-error-message-checks/master/src/burp/match-rules.tab and will return you another result. I suggest you make sure that the response isn't cached.

Additionally it is a little weird that when I press the "Load" button, that all entries are duplicated in the list, maybe remove all entries first before fetching?

**Comment by adetlefsen-rms** [comment]
You have an old version of the plugin. When we switched to Maven builds we needed to change the directory of match-rules.tab to match the Maven standard directory structure. That means it moved from: 
/master/src/burp/match-rules.tab

to: 
/master/src/main/resources/burp/match-rules.tab

Please try loading it from this URL: https://github.com/augustd/burp-suite-error-message-checks/blob/master/src/main/resources/burp/match-rules.tab

**Comment by adetlefsen-rms** [comment]
BTW I sent PortSwigger a pull request to update the version in their BApp store **8 days** ago: 

https://github.com/PortSwigger/error-message-checks/pull/2

Perhaps you can give them a push?

**Comment by floyd-fuh** [comment]
Ah, ok, I see.

Hehe, I don't think I can push anything there, my update is waiting too :) https://github.com/PortSwigger/response-clusterer/pull/1

**Comment by adetlefsen-rms** [comment]
BTW The decision to not delete match rules when loading new match rules was made so that users can load match rules from multiple source files. For example the main match rules loaded from GitHub and a personal or organization set of rules maintained locally.
