### ISSUE TITLE
More regex

### ISSUE THREAD

**Issue by floyd-fuh** [augustd/burp-suite-error-message-checks#12]
How about including some more error messages?

https://github.com/fuzzdb-project/fuzzdb/blob/master/regex/errors.txt

**Comment by augustd** [comment]
I would definitely like to include more of these patterns! But only if I have valid examples of actual error messages to use for the unit tests. 

See: https://github.com/augustd/burp-suite-error-message-checks/blob/master/src/test/resources/burp/testResponse.txt

**Comment by floyd-fuh** [comment]
Google searches turn up quiet a lot of them, such as: 
http://www.sqlteam.com/forums/topic.asp?TOPIC_ID=98697

**Comment by augustd** [comment]
Most of the error messages listed on that page are already picked up by the extension -maybe not completely, but enough to at least flag the page for review by the pentester. 

I've added PR #14 to address the one that was not detected. 

Keep 'em coming!

**Comment by floyd-fuh** [comment]
This is one for the python waitress server:

```
HTTP/1.1 500 Internal Server Error
Content-Type: text/plain
Date: Mon, 13 Feb 2017 14:04:17 GMT
Server: nginx/1.10.1
Content-Length: 110
Connection: Close

Internal Server Error

The server encountered an unexpected internal server error

(generated by waitress)
```

**Comment by augustd** [comment]
Is there any stack trace or additional useful information with the waitress error response? What would be the match string, "(generated by waitress)"?

**Comment by floyd-fuh** [comment]
Hm no, actually I don't know if this belongs into this plugin or into the version check reporter or in none of them. Here's why I think it belongs into one of them: It's nice for a pentester when one of the plugin shows one scan issue information saying that the python waitress server is used (eg. so you can do offline fuzzing of that server, you can search for CVEs for that server, etc.). That's why I suggested it. I don't think its worth the effort to write a new plugin "server fingerprinting" as these two plugins already do something similar. What do you think?

**Comment by floyd-fuh** [comment]
I guess the match string would really be "(generated by waitress)"

**Comment by augustd** [comment]
It doesn't reveal any version numbers and technically it is part of an error message so I guess it belongs in here. 

I've added it to PR #16 with severity "Information" to distinguish from other error messages that include stack traces.

**Comment by floyd-fuh** [comment]
So here's another error message that was not detected by the plugin:

`com.example.some.java.software.with.those.endless.package.names.NotFoundLdapException","softwareError":null,"message":"ldap search failed: LdapSearchObject(baseDN='cn=placeholder1,cn=placeholder2,ou=placeholder3,ou=placeholder4,ou=placeholder5,o=placeholder6,c=placeholder7', scope=SOME, deref=foo, sizeLimit=0, timeLimit=0, filter='(objectClass=someother)', attrs={description})`

This was an LDAP injection in custom code.

I think a good choice would be:
Exception.*cn=.*ou=.*o=.*c=.*
and/or:
Error.*cn=.*ou=.*o=.*c=.*

Both would match in this case.

Btw. I found this with my response cluster plugin (available in BApp), which is helpful when the website often responds with error messages. I often increase max number of clusters from 200 to 500 to get more results but not sure if I should make it the default in the extension yet (performance reasons).

**Comment by augustd** [comment]
I'm not sure I want to match _this specific_ LDAP exception, how about _any_ LDAP object in the response? This expression matches: 

`([dn|dc|cn|ou|uid|o|c]=.*){2,}?`

It looks for two-or-more instances of `<LDAP identifier>=<something>` and it does match the test string you provided. What do you think?

**Comment by floyd-fuh** [comment]
That's fine for me, although I think that it could still match some false positives. Imagine a website which has a login and then prints your LDAP identifiers somewhere.

What I'm not sure is the approach of this extension in general, maybe you can explain. Do you want to only match specific error messages that match specific software which leads to rather low false positive/high false negative or do you want to match generic error messages which leads to rather high false positive/low false negative rate? In my opinion both has a point but different purposes. It's also possible to make it configurable, where low false positive is probably a good default.

So I'm just suggesting (don't worry if you don't like it), but I think a low false positive list (the list you have now) is a good thing, but what would be cool is if this project would also include a second list where less false negatives can occur and has more generic regexes. I know I could already just configure a different list, but a simple button which would switch to a list with more false positives would be cool.

Another option is to keep one list but rate regex via "confidence" (see https://portswigger.net/burp/extender/api/index.html ) and then maybe by default do not look for regex with "tentative" and make it configurable... Not sure what would be best.

I think very often I have two cases during testing:
* A website is pretty silent (often the production website) and shows nearly now error. A list with a lot of regex would be helpful (low false negatives) to catch anything remotely suspicious.
* A website often shows errors (often the test environment). A list with only few but important error messages would be helpful (low false positives) to catch only the most important error messages that might lead to a security issue.

What do you think?

**Comment by augustd** [comment]
I think if an app prints out all of a user's LDAP identifiers you as a pentester would want to know about that... That to me is far more interesting (and indicative of an error) than a random exception name. 

I would like to keep the false positive rate down, but I also don't want many false negatives either (I know, I am chasing unicorns). As the extension is built right now you can configure the individual match rules with any Confidence value you want (See: https://github.com/augustd/burp-suite-error-message-checks/wiki). However, the extension does not offer a way to filter those less-confident results. Burp will still report those matches, they will just show up lower down the list. 

The idea of multiple configurable lists is nice, but that's outside the scope of this particular issue. Please open another issue for that enhancement.

**Comment by augustd** [comment]
I am going to close this issue now, but please do open up new ones if you notice any more error messages!
