### ISSUE TITLE
Include error message regex in issue description

### ISSUE THREAD

**Issue by floyd-fuh** [augustd/burp-suite-error-message-checks#19]
Sometimes I get an issue shown, but the response is very very very long. It is nearly impossible to find the place where the regex matched, as I don't know which regex it was because it is not stated in the issue description. Could we add the regex that matched in the issue description?

**Comment by augustd** [comment]
I'll look into adding that. In the meantime, you should be able to find the string that matched by: 

1. Go to the Issue Report
2. Click the Response tab
3. At the bottom of the UI, click the **>** button

That should take you to the next highlighted match

**Comment by floyd-fuh** [comment]
Good one, I didn't know that! That makes this one a very minor issue, but probably adding the regex in the description might additionally help. Thanks
