### ISSUE TITLE
Extension ignores proxy setings?

### ISSUE THREAD

**Issue by fenceposterror** [augustd/burp-suite-error-message-checks#20]
It seems, like the extension ignores the Upstream Proxy Server config of the user options. Just noticed when trying to get the current list of error message checks. Is that on purpose?

**Comment by augustd** [comment]
It is not _on purpose_ but I have a pretty good idea why it is happening. When the extension loads match rules, it just makes a direct URLConnection to the remote host: 

```
//read match rules from the stream
InputStream is = new URL(url).openStream();
BufferedReader reader = new BufferedReader(new InputStreamReader(is, "UTF-8"));
	    
String str;
while ((str = reader.readLine()) != null) {
    //add the rule
}
```

It is not using `IBurpExtenderCallbacks.makeHttpRequest()`, which uses Burp's internals to issue the request which then presumably respects the upstream proxy configuration, runs passive scans on the response, etc. 

I'm inclined to keep it the way it is unless you have a pretty good reason why you need it changed.

**Comment by augustd** [comment]
@fenceposterror I'm going to close this. If proxy settings are still a problem you can also download the match rules to your local system and then specify a file:/// URL to load them from in the extension.

**Comment by fenceposterror** [comment]
Sorry for not responding quicker. I had used the file URL handler to bypass the restriction. The reason I had asked, is because automatic updates, if you apply them to your list are not possible, and they always need to be downloaded manually, if Burp is used in a network behind a proxy. The setting in Burp is basicly to deal with that. :) That was the reason.

**Comment by adetlefsen-rms** [comment]
Thanks! In that case I will reopen this and look into using Burp's built in functionality to download the match rules.

**Comment by augustd** [comment]
A pull request has been opened in the Portswigger fork. The new version should show up in the BApp store soon.
