### ISSUE TITLE
Detection enhancement.

### ISSUE THREAD

**Issue by notoriousturtle** [augustd/burp-suite-error-message-checks#22]
It detects the following as an error message, from a .js file:

`dispatchException: funct`

**Comment by augustd** [comment]
Is this a false positive? Which regex was matched?

**Comment by notoriousturtle** [comment]
yes, false positive.

**Comment by augustd** [comment]
I've updated the unit tests with better (i.e. some) detection for false positives. Can you please reply with some more context about the false positive you found? A few lines of the script should be enough.

**Comment by augustd** [comment]
Determined that this was matching one of the ASP.net detection patterns. Modified the pattern to be more specific and performant.
