### ISSUE TITLE
Loading rule file from local filesystem

### ISSUE THREAD

**Issue by Hipapheralkus** [augustd/burp-suite-error-message-checks#3]
I'm working in environment, where I don't have access to public facing internet. When I try to download your "match-rules.tab" file from the default URL, nothing happens. When I try to reference it to load from local file system, it doesn't work either.
Could you please add a possibility to browse file system; or at least accept loading from e.g. "C:\match-rules.tab"?  Same goes for burp-suite-software-version-checks

**Comment by adetlefsen-rms** [comment]
A local file should work. Have you tried loading the match rules with a file URL? 

e.g. file:///C|/match-rules.tab

**Comment by Hipapheralkus** [comment]
Thanks, this was exactly what I was looking for:)
