### ISSUE TITLE
False Positive

### ISSUE THREAD

**Issue by geeknik** [augustd/burp-suite-error-message-checks#35]
I'm seeing a `Detailed error Messages Revealed` message in Burp and when I look at the response, this is highlighted: `at (202)` which is part of a phone number, not an error message. The following expressions were matched in the HTTP response: `at ([a-zA-Z0-9_]*\.)*([a-zA-Z0-9_]*)\([a-zA-Z0-9, \[\]\&\;]*\)`

**Comment by augustd** [comment]
@geeknik Thanks for reporting this! I've modified that Regex to fix the false positive. 

Please press Reset to reload your match rules and let me know if it happens again.
