### ISSUE TITLE
False positive in some GWT apps

### ISSUE THREAD

**Issue by dnet** [augustd/burp-suite-error-message-checks#41]
Line 7 contains the following definition:

    at ([a-zA-Z0-9_]*\.)*([a-zA-Z0-9_]+)\([a-zA-Z0-9, \[\]\&\;]*\)	0	ASP.Net	Low	Certain 3

However, this falsely matches normal output of some GWT apps [probably because of this file](https://github.com/akserg/dart_web_toolkit/blob/efc904a8075892a9d6c15ebcb66f831be56662dc/lib/src/ui/ui_object.dart#L14), which include this part: (carets in the line below indicate the part that matched)

    ensure that initWidget() has been called.
             ^^^^^^^^^^^^^^^

How can the above regular expression be modified to avoid such false positives?

**Comment by augustd** [comment]
Thanks @dnet! The expression was matching on the "at" in "that". I changed it to require a word boundary and the false positive is fixed. 

Be sure to reload your match rules to pickup the latest version.
