### ISSUE TITLE
at (\/[A-Za-z0-9\.]+)*\.pm line [0-9]+	rule enhancement

### ISSUE THREAD

**Issue by luh2** [augustd/burp-suite-error-message-checks#48]
Hi,

The following rule 

    \bat ([a-zA-Z0-9_]*\.)*([a-zA-Z0-9_]+)\([a-zA-Z0-9, \[\]\&\;]*\)

matched

     else { // Long format (show items)

in JavaScript files. 
A small suggestion to reduce false positives. Ensure that it would need alternatively to the `\b` a space before the at. Or ensure it is not an alnum character. 

Great work! Thanks.

**Comment by augustd** [comment]
The `\b` should match a word boundary i.e. any non-word character like a space, followed by a word character like the 'a' in at. So this should not have matched unless there was some non-visible character in the response that you received. 

I added  `else { // Long format (show items)` to the [list of false positives](/augustd/burp-suite-error-message-checks/blob/master/src/test/resources/burp/falsePositives.txt) and re-ran the unit tests and there was no match. Can you point me at the actual URL where you got the false positive?

**Comment by luh2** [comment]
I see that I didn't have the newest rules loaded, because they are static from a file, back when https://github.com/augustd/burp-suite-error-message-checks/issues/20 was still an issue. Sorry for the bother.
