### ISSUE TITLE
Upgrade the extension to check active scanner responses

### ISSUE THREAD

**Issue by henshin** [augustd/burp-suite-error-message-checks#5]
While testing your extension I noticed that it doesn't scan results coming from the active scanner.
I think it would be more useful to check those responses than just from the passive scanning, as those will be the ones fuzzed with all kinds of payloads and more likely to throw exceptions.

**Comment by augustd** [comment]
I think you are correct. I was under the assumption that passive scanning of every active scan result was done automatically by Burp, but now I think that may not be the case. I have made a query on the PortSwigger support forum to confirm: 

https://support.portswigger.net/customer/portal/questions/16794671-passive-scanning-of-active-scan-results

If this is true I will update the extension ASAP.

**Comment by augustd** [comment]
PortSwigger has confirmed that passive scan checks only run on the initial response from the active scanner. I am updating the extension to run its checks on all active scan responses, and optionally Repeater and Intruder responses as well.

**Comment by henshin** [comment]
Excelent! I see that you had a very interesting discussion with PortSwigger's support. Looking forward for that new functionality.

**Comment by adetlefsen-rms** [comment]
@henshin, If you get a chance please test out the latest pull request and let me know if it works as you'd expect now.

**Comment by henshin** [comment]
@adetlefsen-rms Unfortunately, It doesn't seem to be working as expected yet.
I made a very simple PHP script to simulate errors which has the following content:
```
<?php
$n="\n";
if(isset($_GET['c'])){
	$c = $_GET['c'];
	print "$c$n";
	if($c=='AABBCCDDX'){
		print "Something and nested expection is Something!";
	}else if($c=="sleep(20)"){
		print "Use of uninitialized value in string eq at /Library/Perl/5.8.6/WWW/Mechanize.pm line 695";
	}
}
?>
```
I picked some fixed payloads that Burp always performs on active scans and outputted some error messages when they hit (I was using test.php?c=AABBCCDD format)
Then I scanned it using Burp and it didn't detect any issues with error messages.
Can you try it on your end and let me know your results?

**Comment by adetlefsen-rms** [comment]
Are you sure you are looking at the `scan_active_responses` branch? 

Do you have this test script online somewhere I can hit it? I tested by scanning the login form at http://demo.testfire.net/ and it correctly picked up the `System.Data.OleDb.OleDbException` SQL error message after a few hits. 

Also note that adding scan issues with `IBurpExtenderCallbacks.addScanIssue()` does not appear to add issues directly on the Scanner tab, but they do show up on the Target tab.

**Comment by henshin** [comment]
You're totally right, I forgot to clone the right branch :)
It's working great! Good job with this one. I'm sure it will be useful in the future.
