### ISSUE TITLE
SQLServerException + bad SQL grammar + Error querying database

### ISSUE THREAD

**Issue by drwetter** [augustd/burp-suite-error-message-checks#66]
Those were in one error message from a Java application using JDBC --> MSSQL where I fuzzed some params, so the best would be to add each of those

**Comment by drwetter** [comment]
Let me know if I better submit a PR

**Comment by augustd** [comment]
Yes, please send a PR!

If possible, please include the original error message so we can use it for
the unit tests.

**Comment by drwetter** [comment]
I noticed a couple of things while working on the PR. First some rules in the tab file are labeled rather on the  generous side. An error messages like those:

![image](https://github.com/augustd/burp-suite-error-message-checks/assets/8036727/af10b1ea-bc71-4e37-a8d5-b19ec3493528)


are to me strong indicators of an SQL injection. I would not label them as `Low``.  There are defitely High.

Then not sure how the parser works for the first column. Some chars are quoted some not., like ``/`` in ``\.php</b> ``, sometimes there's a not quoted dot ``SQLite.Exception``. The latter would work anyway but ...

**Comment by augustd** [comment]
SQL Injection itself would be a High severity vulnerability. An error message which indicates SQL Injection is still Low severity until the tester confirms it. 

I changed these to Medium, Certain rather than High, Firm.

**Comment by augustd** [comment]
Thanks for your submission! Keep them coming..

**Comment by drwetter** [comment]
> SQL Injection itself would be a High severity vulnerability. An error message which indicates SQL Injection is still Low severity until the tester confirms it.

Don't want to sound disrespectful but: no.  It's not how any tool or pen testing works nowadays.

Just have a closer look what burp labels during automated scanning as High or Critical. 

Common sense is a tool should point out security problems which **always** need to be confirmed manually. If you start labeling possible critical flaws as low, there's a high probability that it won't be even considered as to be checked manually. Also good testers are supposed to look at findings labeled low but if there's a tester with not so much experience or budget is not sufficient or you have too many findings it's getting lost.

If one is unsure, one can adjust the certainty to ~firm.
